
-- 테이블 삭제
DROP TABLE CUSTOMER;
DROP TABLE BANK;

-- BANK 테이블 생성
CREATE TABLE BANK (
    BANK_CODE VARCHAR2 (20 BYTE) NOT NULL, -- PK
    BANK_NAME VARCHAR2 (30 BYTE) NULL
);

-- CUSTOMER 테이블 생성
CREATE TABLE CUSTOMER (
    NO        NUMBER             NOT NULL,-- PK
    NAME      VARCHAR2 (30 BYTE) NOT NULL, -- 필수
    PHONE     VARCHAR2 (30 BYTE) UNIQUE, -- 중복불가
    AGE       NUMBER             CHECK(AGE BETWEEN 0 AND 100), -- CK 0 ~ 100
    BANK_CODE VARCHAR2 (20 BYTE) -- FK : 외래키에는 가급적 NOT NULL 하지 않는다.
);

-- 기본키 추가
ALTER TABLE BANK ADD CONSTRAINT PK_BANK PRIMARY KEY (BANK_CODE);
ALTER TABLE CUSTOMER ADD CONSTRAINT PK_CUSTOMER PRIMARY KEY (NO);

-- 외래키 추가
ALTER TABLE CUSTOMER
    ADD CONSTRAINT FK_CUSTOMER_BANK FOREIGN KEY (BANK_CODE) REFERENCES BANK(BANK_CODE)
        ON DELETE CASCADE;
        -- ON DELETE SET NULL : 외래키 NULL 허용 (* 이 기능이 없다면, 회원탈퇴가 불가능해진다.)
        