-- (CTRL + / ) 주석 달기

/*
    1 : M 관계의 테이블 생성
    
    1. 명칭
        1) 부모 테이블 : 일( 1 ), PK를 가진 테이블
        2) 자식 테이블 : 다(M), FK를 가진 테이블
    
    2. 생성
        부모 테이블을 먼저 생성한 후 , 자식 테이블을 나중에 생성
        ( 생성 : 부모 → 자식 )
    
    3. 삭제
        자식 테이블을 먼저 삭제 후, 부모 테이블을 나중에 삭제
        ( 삭제 : 자식 → 부모 )
*/

-- 학교 테이블  (부모 테이블 : PK를 가진 테이블 )
DROP TABLE SCHOOL;
CREATE TABLE SCHOOL(
    SCH_CODE NUMBER( 1 ) NOT NULL PRIMARY KEY,
    SCH_NAME VARCHAR2( 20 BYTE ) NOT NULL
);
   
-- 
DROP TABLE SCHOOL;
CREATE TABLE SCHOOL(
    SCH_CODE NUMBER( 1 ) NOT NULL,
    SCH_NAME VARCHAR2( 20 BYTE ) NOT NULL,
    PRIMARY KEY (SCH_CODE)
); 

--
DROP TABLE SCHOOL;
CREATE TABLE SCHOOL(
    SCH_CODE NUMBER( 1 ) NOT NULL CONSTRAINT PK_SCHOOL PRIMARY KEY,
    SCH_NAME VARCHAR2( 20 BYTE ) NOT NULL
); 

--
DROP TABLE SCHOOL;
CREATE TABLE SCHOOL(
    SCH_CODE NUMBER( 1 ) NOT NULL,
    SCH_NAME VARCHAR2( 20 BYTE ) NOT NULL,
    CONSTRAINT PK_SCHOOL PRIMARY KEY (SCH_CODE)
);

-- 학생 테이블 ( 자식 테이블 : FK를 가진 테이블 )
DROP TABLE STUDENT;
CREATE TABLE STUDENT (
    STU_NO CHAR( 5 BYTE ) NOT NULL PRIMARY KEY,
    SCH_CODE NUMBER( 1 ) NOT NULL REFERENCES SCHOOL ( SCH_CODE),    -- 외래키 지정
    STU_NAME VARCHAR2 ( 20 BYTE ) NULL
);

--
DROP TABLE STUDENT;
CREATE TABLE STUDENT (
    STU_NO CHAR( 5 BYTE ) NOT NULL,
    SCH_CODE NUMBER( 1 ) NOT NULL,
    STU_NAME VARCHAR2 ( 20 BYTE ) NULL,
    PRIMARY KEY (STU_NO),
    FOREIGN KEY (SCH_CODE) REFERENCES SCHOOL
);

DROP TABLE STUDENT;
CREATE TABLE STUDENT (
    STU_NO CHAR( 5 BYTE ) NOT NULL,
    SCH_CODE NUMBER( 1 ) NOT NULL,
    STU_NAME VARCHAR2 ( 20 BYTE ) NULL,
    CONSTRAINT PK_STUDENT PRIMARY KEY (STU_NO),
    CONSTRAINT FK_STUDENT_SCHOOL FOREIGN KEY (SCH_CODE) REFERENCES SCHOOL  -- FK_STUDENT와 SCHOOL을 연결하는 외래키  (30자까지 허용되므로, 길 경우 축약)
);

-- 최종 정리
-- 생성 : 부모 먼저, 자식 나중
-- 삭제 :  자식 먼저, 부모 나중
DROP TABLE SCHOOL;
DROP TABLE STUDENT;

CREATE TABLE SCHOOL(
  SCH_NO NUMBER ( 1 ) NOT NULL,
  SCH_NAME VARCHAR2 ( 20 BYTE ) NOT NULL,
  CONSTRAINT PK_SCHOOL PRIMARY KEY (SCH_NO)
);

CREATE TABLE STUDENT (
 STU_NO CHAR ( 5 BYTE ) NOT NULL,
 SCH_CODE NUMBER ( 1 ) NOT NULL,
 STU_NAME VARCHAR2 ( 20 BYTE ) NULL,
 CONSTRAINT PK_STUDENT PRIMARY KEY (STU_NO),
 CONSTRAINT FK_STUDENT_SCHOOL FOREIGN KEY (SCH_CODE) REFERENCES SCHOOL
);