-- 연습문제
/*
    수강신청
    1. 여러 학생이 여러 과목을 신청하는 다대다관계
    2. 학생-과목의 직접적인 다대다관계 설정은 불가능
    3. 학생-수강신청-과목으로 일대다관계 2개 설정으로 진행
*/
/*
    참고. 외래키 제약조건을 무시하고 테이블 삭제
    순서에 상관없이 삭제할 수 있음
    DROP TABLE STUDENT CASCADE CONSTRAINTS;
    DROP TABLE SUBJECT CASCADE CONSTRAINTS;
    DROP TABLE ENROLL  CASCADE CONSTRAINTS;
*/

DROP TABLE REGISTRATION;
DROP TABLE SUBJECT;
DROP TABLE STUDENT;



CREATE TABLE STUDENT (
     STU_NO CHAR ( 5 BYTE ) NOT NULL,
     STU_NAME VARCHAR2 ( 20 BYTE ) NOT NULL,
     STU_AGE NUMBER ( 3 ) NOT NULL,
     CONSTRAINT CK_STU_AGE CHECK (STU_AGE BETWEEN 0 AND 100),
     CONSTRAINT PK_STUDENT PRIMARY KEY (STU_NO)
);



CREATE TABLE SUBJECT (
     SUB_CODE CHAR ( 5 BYTE ) NOT NULL,
     SUB_NAME VARCHAR2 ( 20 BYTE ) NOT NULL,
     SUB_PROFESSOR VARCHAR2 ( 20 BYTE ) NOT NULL,
     CONSTRAINT PK_SUBJECT PRIMARY KEY (SUB_CODE)
);


CREATE TABLE REGISTRATION (
    REG_REGNUM NUMBER ( 3 ) NOT NULL,
    REG_NO CHAR ( 5 BYTE ) NOT NULL,
    REG_CODE CHAR ( 1 BYTE ) NOT NULL,
    CONSTRAINT PK_REGISTRATION PRIMARY KEY (REG_REGNUM),
    CONSTRAINT FK_REG_STUDENT FOREIGN KEY (REG_NO) REFERENCES STUDENT(STU_NO),
    CONSTRAINT FK_REG_SUBJECT FOREIGN KEY (REG_CODE) REFERENCES SUBJECT(SUB_CODE)
);