DROP TABLE PROCEEDING;
DROP TABLE EMPLOYEE;
DROP TABLE PROJECT;
DROP TABLE DEPARTMENT;

-- 부서 테이블
CREATE TABLE DEPARTMENT (
    DEPT_NO VARCHAR2 (15 BYTE) NOT NULL, -- PK
    DEPT_NAME VARCHAR2 (30 BYTE) NULL,
    DEPT_LOCATION VARCHAR2 (50 BYTE) NULL
);

-- 프로젝트 테이블
CREATE TABLE PROJECT (
    PJT_NO NUMBER NOT NULL, -- PK
    PJT_NAME VARCHAR2 (30 BYTE) NULL,
    BEGIN_DATE DATE NULL,
    END_DATE DATE NULL  
);

-- 사원 테이블
CREATE TABLE EMPLOYEE (
    EMP_NO NUMBER NOT NULL, -- PK
    DEPT_NO VARCHAR2 (15 BYTE) NULL,
    POSITION CHAR (10 BYTE) NULL,
    NAME VARCHAR2 (15 BYTE) NULL,
    HIRE_DATE DATE NULL,
    SALARY NUMBER NULL
);


-- 프로젝트 진행 테이블
CREATE TABLE PROCEEDING (
    PCD_NO NUMBER NOT NULL,-- PK
    EMP_NO NUMBER NULL, -- FK
    PJT_NO NUMBER NULL, -- FK
    PJT_STATE NUMBER NOT NULL
);

-- 기본키 추가
ALTER TABLE DEPARTMENT
    ADD CONSTRAINT PK_DEPARTMENT PRIMARY KEY (DEPT_NO);
    
ALTER TABLE PROJECT
    ADD CONSTRAINT PK_PROJECT PRIMARY KEY (PJT_NO);
    
ALTER TABLE EMPLOYEE
    ADD CONSTRAINT PK_EMP_NO PRIMARY KEY (EMP_NO);
    
ALTER TABLE PROCEEDING
    ADD CONSTRAINT PK_PROCEEDING PRIMARY KEY (PCD_NO);
    
-- 외래키 추가
ALTER TABLE EMPLOYEE
    ADD CONSTRAINT FK_EMPLOYEE_DEPARTMENT FOREIGN KEY(DEPT_NO)
        REFERENCES DEPARTMENT (DEPT_NO);

ALTER TABLE PROCEEDING
    ADD CONSTRAINT FK_PROCEEDING_PROJECT FOREIGN KEY (PJT_NO)
        REFERENCES PROJECT (PJT_NO);
    
ALTER TABLE PROCEEDING
    ADD CONSTRAINT FK_PROCEEDING_EMPLOYEE FOREIGN KEY (EMP_NO)
        REFERENCES EMPLOYEE (EMP_NO);

-- 외래키 제거
-- DEPARTMENT 테이블의 DEPT_NO 칼럼을 참조하는 외래키 제약조건을 제거해야
-- DEPARTMENT 테이블의 DEPT_NO 칼럼에 추가된 기본키 제약조건을 제거할 수 있다.
ALTER TABLE EMPLOYEE
    DROP CONSTRAINT FK_EMPLOYEE_DEPARTMENT;    

-- 기본키 제거
ALTER TABLE PROCEEDING
    DROP CONSTRAINT PK_PROCEEDING;
    
ALTER TABLE DEPARTMENT
    DROP CONSTRAINT PK_DEPARTMENT;
/* 
    ALTER TABLE DEPARTMENT
        DROP PRIMARY KEY;
    이름을 모를 경우, 기본키(PK)는  DROP PRIMARY KEY; 로 삭제 가능        
    FK에 의해 참조되는 PK는 제거할 수 없으므로, 먼저 FK를 제거한다
*/ 