-- 테이블 삭제
DROP TABLE LECTURE;
DROP TABLE ENROLL; -- 수강신청
DROP TABLE STUDENT;
DROP TABLE COURSE; -- 과목
DROP TABLE PROFESSOR;

-- 테이블 생성
CREATE TABLE PROFESSOR (
    PRO_NO   NUMBER NOT NULL, --PK, 교수번호
    PRO_NAME VARCHAR2(15 BYTE), --교수이름
    PRO_DEPT VARCHAR2(30 BYTE) --교수전공
);

CREATE TABLE COURSE ( --과목
    COUR_NO    NUMBER NOT NULL, --PK, 과목번호
    COUR_NAME  VARCHAR2 (30 BYTE), --과목명
    COUR_SCORE NUMBER --이수학점
);

CREATE TABLE STUDENT (
    STU_NO    NUMBER NOT NULL, --PK, 학번
    STU_NAME  VARCHAR2(15 BYTE), --이름
    STU_ADDR  VARCHAR2(100 BYTE), --주소
    STU_CLASS NUMBER(1), --학년
    PRO_NO    NUMBER --FK_STUDENT_PROFESSOR, 담당교수번호
);

CREATE TABLE ENROLL ( --수강신청
    ENR_NO   NUMBER NOT NULL, --PK, 수강신청번호
    STU_NO   NUMBER, --FK_ENROLL_STUDENT, 학생학번
    COUR_NO  NUMBER, --FK_ENROLL_COURSE, 과목번호
    ENR_DATE DATE --신청일자
);

CREATE TABLE LECTURE ( --강의
    LEC_NO NUMBER NOT NULL, --PK, 강의번호
    PRO_NO NUMBER, --FK_LECTURE_PROFESSOR, 교수번호
    ENR_NO NUMBER, --FK_LECTURE_ENROLL, 수강신청번호
    LEC_NAME VARCHAR2(30 BYTE), --강의 이름
    LEC_LOCATION VARCHAR2(15 BYTE) --강의실
);

-- 기본키 설정
ALTER TABLE PROFESSOR
    ADD CONSTRAINT PK_PROFESSOR PRIMARY KEY (PRO_NO);
ALTER TABLE COURSE
    ADD CONSTRAINT PK_COURSE PRIMARY KEY (COUR_NO);
ALTER TABLE STUDENT
    ADD CONSTRAINT PK_STUDENT PRIMARY KEY (STU_NO);
ALTER TABLE ENROLL
    ADD CONSTRAINT PK_ENROLL PRIMARY KEY (ENR_NO);
ALTER TABLE LECTURE
    ADD CONSTRAINT PK_LECTURE PRIMARY KEY (LEC_NO);

-- 외래키 설정
ALTER TABLE STUDENT
    ADD CONSTRAINT FK_STUDENT_PROFESSOR FOREIGN KEY (PRO_NO)
        REFERENCES PROFESSOR (PRO_NO);
        
ALTER TABLE ENROLL
    ADD CONSTRAINT FK_ENROLL_STUDENT FOREIGN KEY (STU_NO)
        REFERENCES STUDENT (STU_NO);
ALTER TABLE ENROLL
    ADD CONSTRAINT FK_ENROLL_COURSE FOREIGN KEY (COUR_NO)
        REFERENCES COURSE (COUR_NO);
        
ALTER TABLE LECTURE
    ADD CONSTRAINT FK_LECTURE_PROFESSOR FOREIGN KEY (PRO_NO)
        REFERENCES PROFESSOR (PRO_NO);
ALTER TABLE LECTURE
    ADD CONSTRAINT FK_LECTURE_ENROLL FOREIGN KEY (ENR_NO)
        REFERENCES ENROLL (ENR_NO);