-- 시퀀스
DROP SEQUENCE BOARD_SEQ;
CREATE SEQUENCE BOARD_SEQ NOCACHE;

-- 테이블
DROP TABLE BOARD;
CREATE TABLE BOARD(
    BOARD_NO    NUMBER NOT NULL,   --PK
    NAME        VARCHAR2 (20 BYTE) NOT NULL,
    TITLE       VARCHAR2 (100 BYTE) NOT NULL,
    CONTENT     VARCHAR2 (400 BYTE),
    CREATE_DATE DATE,
    CONSTRAINT PK_BOARD PRIMARY KEY (BOARD_NO)
);

INSERT INTO BOARD
	VALUES
		(BOARD_SEQ.NEXTVAL, '회원1', '가입인사', '안녕', SYSDATE);
COMMIT;