# yaml/yml (야믈) 파일 수동변환
# 구분 : 마침표(.)가 아니라 콜론(:) 후 공백 2칸

# STS3 와 달리 조각난 정보를 application.properties에 저장
# jsp 파일을 사용하지 않으므로 servlet-context.xml 삭제
# 콜론(:) 뒤 공백 사용 가능

# server.port
# web.xml
# session (1800 sescons = 30 minutes)
server:
  port: 9090
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    session:
      timeout: 1800

# database connection
spring:
  datasource:
    hikari:
      driver-class-name: oracle.jdbc.OracleDriver
      jdbc-url: jdbc:oracle:thin:@localhost:1521:xe
      username: SCOTT
      password: TIGER

# mybatis
mybatis:
  config-location: mybatis/config/mybatis-config.xml
  mapper-locations: mybatis/mapper/*.xml

